// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  donation_slice: dynamic(() => import("./DonationSlice")),
  donor_hero: dynamic(() => import("./DonorHero")),
  frequently_asked_questions: dynamic(
    () => import("./FrequentlyAskedQuestions"),
  ),
  hero: dynamic(() => import("./Hero")),
  icon_showcase: dynamic(() => import("./IconShowcase")),
  image_showcase: dynamic(() => import("./ImageShowcase")),
  initiative_showcase: dynamic(() => import("./InitiativeShowcase")),
  magic_section: dynamic(() => import("./MagicSection")),
  mission_vision: dynamic(() => import("./MissionVision")),
  mission_vision_showcase: dynamic(() => import("./MissionVisionShowcase")),
  our_partners: dynamic(() => import("./OurPartners")),
  our_team: dynamic(() => import("./OurTeam")),
  page_title: dynamic(() => import("./PageTitle")),
  partners_showcase: dynamic(() => import("./PartnersShowcase")),
  program_showcase: dynamic(() => import("./ProgramShowcase")),
  rotating_carousel: dynamic(() => import("./RotatingCarousel")),
  tab_slice: dynamic(() => import("./TabSlice")),
  testimonial: dynamic(() => import("./Testimonial")),
  text_showcase: dynamic(() => import("./TextShowcase")),
  tilted_cards: dynamic(() => import("./TiltedCards")),
  timeline_scroller: dynamic(() => import("./TimelineScroller")),
};
