name: Debit Invoices

on:
  schedule:
      # Run at 4:30 PM IST (11:00 UTC)
     - cron: "30 11 * * *"

  workflow_dispatch: # Allow manual trigger for testing

jobs:
  debit:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Debit Cron API
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.CRON_SECRET }}" \
            -H "Content-Type: application/json" \
            https://dev.akanksha.org/api/debit-invoices
