name: Monthly Invoices

on:
  schedule:
   
     - cron: "30 0 * * *"

  workflow_dispatch:        # Allows manual runs
    
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Call invoice generation API
        run: |
          curl -X POST https://dev.akanksha.org/api/generate-monthly-invoices \
            -H "Authorization: Bearer ${{ secrets.CRON_SECRET }}"